spring:
  application:
    name: TorrentBot
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb://mKK:mon3jn@1:27017/BotDB?authSource=admin&authMechanism=SCRAM-SHA-256
      database: BotDB
  redis:
    host:
    port: 6379
    password: WtQxKK
    database: 0

bot:
  options:
    admins:
    token:
    username:

qb:
  options:
    host:
    username:
    password:
    tag: tg-download
    category: DS
    download-path: /media/av

alist:
  options:
    host:
    username: admin
    password:
    src-path: /下载/
    target-path: /media/local/整理

logging:
  level:
    root: INFO
    org.springframework: INFO
    tdck.qdz.torrentbot: DEBUG
    tdck.qdz.torrentbot.service.QbService: DEBUG 